
//! Autogenerated weights for `pallet_legacy`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-21, STEPS: `3`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `fedora`, CPU: `AMD Ryzen 9 7950X 16-Core Processor`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_legacy
// --extrinsic
// *
// --steps
// 3
// --repeat
// 1
// --output
// pallets/legacy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use crate::*;

pub trait WeightInfo {
	fn create_secret() -> Weight;
}

/// Weight functions for `pallet_legacy`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: Legacy Nonce (r:1 w:1)
	/// Proof Skipped: Legacy Nonce (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Legacy OwnerMap (r:1 w:1)
	/// Proof Skipped: Legacy OwnerMap (max_values: None, max_size: None, mode: Measured)
	/// Storage: Legacy SecretMap (r:0 w:1)
	/// Proof Skipped: Legacy SecretMap (max_values: None, max_size: None, mode: Measured)
	/// The range of component `b` is `[1, 10]`.
	fn create_secret() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `178`
		//  Estimated: `6977`
		// Minimum execution time: 9_117_000 picoseconds.
		Weight::from_parts(10_412_737, 0)
			.saturating_add(Weight::from_parts(0, 6977))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
